---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
  labels:
    app: test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
      annotations:
        vault.hashicorp.com/role: test-app
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-inject-direct: 'true'
        vault.hashicorp.com/agent-inject-secret-test-user: secret/data/test-app#.Data.data.user
        vault.hashicorp.com/agent-inject-as-env-test-user: TEST_USER
        vault.hashicorp.com/agent-inject-secret-test-password: secret/data/test-app#.Data.data.password
        vault.hashicorp.com/agent-inject-as-env-test-password: TEST_PASSWORD
    spec:
      serviceAccountName: test-app-sa
      containers:
      - name: test-app
        image: test-app
        imagePullPolicy: IfNotPresent
